# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from melle/SensorData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SensorData(genpy.Message):
  _md5sum = "ac7363d784144c7402ac7de3955b5772"
  _type = "melle/SensorData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 binFullness
int8 batteryLevel
int8 signalStrength
float64 latitude
float64 longitude
"""
  __slots__ = ['binFullness','batteryLevel','signalStrength','latitude','longitude']
  _slot_types = ['int8','int8','int8','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       binFullness,batteryLevel,signalStrength,latitude,longitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.binFullness is None:
        self.binFullness = 0
      if self.batteryLevel is None:
        self.batteryLevel = 0
      if self.signalStrength is None:
        self.signalStrength = 0
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
    else:
      self.binFullness = 0
      self.batteryLevel = 0
      self.signalStrength = 0
      self.latitude = 0.
      self.longitude = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3b2d.pack(_x.binFullness, _x.batteryLevel, _x.signalStrength, _x.latitude, _x.longitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.binFullness, _x.batteryLevel, _x.signalStrength, _x.latitude, _x.longitude,) = _struct_3b2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3b2d.pack(_x.binFullness, _x.batteryLevel, _x.signalStrength, _x.latitude, _x.longitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.binFullness, _x.batteryLevel, _x.signalStrength, _x.latitude, _x.longitude,) = _struct_3b2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3b2d = struct.Struct("<3b2d")
