// Generated by gencpp from file melle/AndroidSensorData.msg
// DO NOT EDIT!


#ifndef MELLE_MESSAGE_ANDROIDSENSORDATA_H
#define MELLE_MESSAGE_ANDROIDSENSORDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melle
{
template <class ContainerAllocator>
struct AndroidSensorData_
{
  typedef AndroidSensorData_<ContainerAllocator> Type;

  AndroidSensorData_()
    : latitude(0.0)
    , longitude(0.0)
    , azimuth(0.0)
    , roll(0.0)
    , pitch(0.0)  {
    }
  AndroidSensorData_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , azimuth(0.0)
    , roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _azimuth_type;
  _azimuth_type azimuth;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;




  typedef boost::shared_ptr< ::melle::AndroidSensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melle::AndroidSensorData_<ContainerAllocator> const> ConstPtr;

}; // struct AndroidSensorData_

typedef ::melle::AndroidSensorData_<std::allocator<void> > AndroidSensorData;

typedef boost::shared_ptr< ::melle::AndroidSensorData > AndroidSensorDataPtr;
typedef boost::shared_ptr< ::melle::AndroidSensorData const> AndroidSensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melle::AndroidSensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melle::AndroidSensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace melle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'melle': ['/home/nima/Code/Ros/melle_ws/src/melle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::melle::AndroidSensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melle::AndroidSensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melle::AndroidSensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melle::AndroidSensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melle::AndroidSensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melle::AndroidSensorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melle::AndroidSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "372a806ca71ccc42a8e0620fd67a7fcf";
  }

  static const char* value(const ::melle::AndroidSensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x372a806ca71ccc42ULL;
  static const uint64_t static_value2 = 0xa8e0620fd67a7fcfULL;
};

template<class ContainerAllocator>
struct DataType< ::melle::AndroidSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melle/AndroidSensorData";
  }

  static const char* value(const ::melle::AndroidSensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melle::AndroidSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n\
float64 longitude\n\
float64 azimuth\n\
float64 roll\n\
float64 pitch\n\
";
  }

  static const char* value(const ::melle::AndroidSensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melle::AndroidSensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.azimuth);
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AndroidSensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melle::AndroidSensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melle::AndroidSensorData_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "azimuth: ";
    Printer<double>::stream(s, indent + "  ", v.azimuth);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELLE_MESSAGE_ANDROIDSENSORDATA_H
