// Generated by gencpp from file melle/SensorData.msg
// DO NOT EDIT!


#ifndef MELLE_MESSAGE_SENSORDATA_H
#define MELLE_MESSAGE_SENSORDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace melle
{
template <class ContainerAllocator>
struct SensorData_
{
  typedef SensorData_<ContainerAllocator> Type;

  SensorData_()
    : binFullness(0)
    , batteryLevel(0)
    , signalStrength(0)
    , latitude(0.0)
    , longitude(0.0)  {
    }
  SensorData_(const ContainerAllocator& _alloc)
    : binFullness(0)
    , batteryLevel(0)
    , signalStrength(0)
    , latitude(0.0)
    , longitude(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _binFullness_type;
  _binFullness_type binFullness;

   typedef int8_t _batteryLevel_type;
  _batteryLevel_type batteryLevel;

   typedef int8_t _signalStrength_type;
  _signalStrength_type signalStrength;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;




  typedef boost::shared_ptr< ::melle::SensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::melle::SensorData_<ContainerAllocator> const> ConstPtr;

}; // struct SensorData_

typedef ::melle::SensorData_<std::allocator<void> > SensorData;

typedef boost::shared_ptr< ::melle::SensorData > SensorDataPtr;
typedef boost::shared_ptr< ::melle::SensorData const> SensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::melle::SensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::melle::SensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace melle

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'melle': ['/home/nima/Code/Ros/melle_ws/src/melle/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::melle::SensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::melle::SensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melle::SensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::melle::SensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melle::SensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::melle::SensorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::melle::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac7363d784144c7402ac7de3955b5772";
  }

  static const char* value(const ::melle::SensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac7363d784144c74ULL;
  static const uint64_t static_value2 = 0x02ac7de3955b5772ULL;
};

template<class ContainerAllocator>
struct DataType< ::melle::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "melle/SensorData";
  }

  static const char* value(const ::melle::SensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::melle::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 binFullness\n\
int8 batteryLevel\n\
int8 signalStrength\n\
float64 latitude\n\
float64 longitude\n\
";
  }

  static const char* value(const ::melle::SensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::melle::SensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.binFullness);
      stream.next(m.batteryLevel);
      stream.next(m.signalStrength);
      stream.next(m.latitude);
      stream.next(m.longitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::melle::SensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::melle::SensorData_<ContainerAllocator>& v)
  {
    s << indent << "binFullness: ";
    Printer<int8_t>::stream(s, indent + "  ", v.binFullness);
    s << indent << "batteryLevel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.batteryLevel);
    s << indent << "signalStrength: ";
    Printer<int8_t>::stream(s, indent + "  ", v.signalStrength);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MELLE_MESSAGE_SENSORDATA_H
